before_install:
  - sudo apt-get update qq
  - sudo apt-get install -y libgtk2.0-dev
language c:
compiler:
  - gcc
script: ./autogen.sh && ./configure && make

language ruby:
rvm:
  - 2.1.0
  - 1.9.0
  - 1.8.7

before_install:
  - sudo apt-get install -y ruby-gnome2-dev
script: ruby extconf.rb && make