before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ruby-dev ruby ruby-gnome2-dev libgtk2.0-dev

language: c
compiler:
  - gcc

script: ./autogen.sh && ./configure --ruby=/usr/bin/ruby --enable-ruby && make
